# Plugins
gems:
- jekyll-sitemap
safe: false

# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENSE.txt', 'CNAME']


# Site Settings
title: "CPPP Conference"
email: "cppp@gmail.com"
description: "A C++ Conference in the heart of Paris"
baseurl: ""
url: "https://cppp.fr"
permalink: "/blog/:title"
googleAnalyticsTrackingId: "UA-149463947-1"
googleAnalyticsSiteUrl: "cppp.fr"
#siteVerification: "b9imDOrFawXaBXCC4r3uJDdswSYcalD-wWpMYhFq-no"

# Organizer Info
organizerName: "C++FrUG"
organizerAlternateName: "C++ French User Group"
organizerDescription: "Open and volunteer geek communities who create exciting projects and share experience about Google technology with passion."
organizerEmail: "contact@cppp.fr"
organizerLogo: "/img/seo/organizer-logo.png"
organizerLink: "http://cppfrug.org/"

# Head
metaKeywords: "event, C++, CPPP, programming, developers, France, Paris"
twitterAccount: "@CpppFr"
socialImageSrcGooglePlus: "/img/seo/sharing-google-plus.png"
socialImageSrcTwitter: "/img/seo/sharing-twitter.png"
socialImageSrcFacebook: "/img/seo/sharing-facebook.png"

# Documents
#c4pUrl: "https://bit.ly/dfua-c4p"
#c4sponsorsUrl: "/assets/GDG_DevFest_Partnership.pdf"


# Navigation
navigationLinks:
 - {permalink: "/", text: "Home"}
 - {permalink: "/blog/", text: "Blog"}
 - {permalink: "/team/", text: "Team"}
 - {permalink: "/logistics/", text: "Logistics"}
#bottomNavigationLinks:
# - {link: "https://bit.ly/dfua-c4p", text: "Become a speaker"}
#rightNavigationButtons:
# - {link: "https://bit.ly/dfua-c4p", text: "Become a speaker"}

# Hero Block
heroImage: "header.png"
heroTitle: "CPPP 2020"
eventDate: "June 22-23, 2020"

# About Block
aboutTitle: "An international C++ conference in the heart of Paris"
aboutBlock:
 - {title: "Progress", image: "progress.jpg", text: "Whatever their expertise, every C++ programmer is in the process of learning C++ and making progress. This track is dedicated to learning and reinforcing basic C++ knowledge and understanding. These talks are accessible to beginners and experts alike." }
 - {title: "Produce", image: "produce.jpg", text: "C++ is a decades-old language that is used in many industries. Everyday, C++ programmers are working with code bases that were started years or decades ago and represent millions of lines of code, with the legacy and bugs it implies. This track is dedicated to sharing solutions to produce and maintain reliable software using C++." }
 - {title: "Push Forward", image: "push.jpg", text: "C++ is a lively language that keeps on evolving and changing. We are still discovering new ways of using the existing language while the C++ committee is making it evolve. In this track, we share new patterns and functionality that C++ has or might acquire in the future." }

# Latest News Block
latestNewsTitle: "Latest news"

# Rockstar Speakers Block
rockstarSpeakersImage: "rockstar-speakers.jpg"
rockstarSpeakersCount: 4
rockstarSpeakersTitle: "Speakers"
rockstarSpeakersButtonText: "See all speakers"

# Location Block
locationBlockTitle: "Location"
eventLocationName: "UIC-P"
eventLocationLink: "http://uicp.fr/"
eventStreetAddress: "16 Rue Jean Ney"
eventAddressLocality: "Paris"
eventAddressLocalityRegion: "Paris"
eventPostalCode: "75015"
eventAddressCountry: "Paris"
eventStartTime: "2020-06-22T08:00"
eventDoorTime: "09:00"
eventEndTime: "2020-06-23T20:00"
eventPlaceCoordinates: "48.8553124, 2.291616"
mapCenterCoordinates: "48.8553294, 2.2896747"
mapMobileCenterCoordinates: "48.8553294, 2.2896747"

# Venue Block
venueBlockTitle: "Venue"
venueBigImage: "venue_0.jpg"
venueSmallImage1: "venue_1.jpg"
venueSmallImage2: "venue_2.jpg"
venueSmallImage3: "venue_3.jpg"
venueTitle: "UIC-P"
venueFeatures: ["Fully accessible to people with reduced mobility", "Near the Eiffel Tower"]

# Tweets Feed Block
tweetsFeedImage: "twitter-feed.jpg"
tweetsFeedTitle: "What's Up?"
twitterHashTag: "CpppFr"
#twitterFeed: "http://lviv.gdg.org.ua/tweetledee/favoritesjson.php?c=10&cache_interval=8000"

# Partners Block
sponsorsTitle: "Our Sponsors"
partnersC4sponsorsButton: "Become a sponsor"

# Subscribe Block
subscribeImage: "subscribe.jpg"
subscribeTitle: "Subscribe for updates"
subscribeAction: "https://gmail.us20.list-manage.com/subscribe/post?u=130c30392a41c9cf6f1a92e01&amp;id=75d0efaeaf"
subscribeInfo: "Registration will be open around end of August. Number of tickets are limited. Stay tuned!"

# Footer
socialLinks:
 - {link: "https://twitter.com/intent/user?screen_name=CpppFr", icon: "twitter"}
 - {link: "https://facebook.com/Cpppfr", icon: "facebook"}
 - {permalink: "/feed.xml", icon: "rss"}
footerBlocks:
 -
  title: "Links"
  links:
   - {link: "https://www.youtube.com/channel/UChti8oyWC3oW91LpfZ2bmSQ", text: "CPPP Youtube Channel"}
   - {link: "https://github.com/cppp-france/CPPP-19", text: "Conference slides"}
   - {link: "http://cppfrug.org/", text: "C++ FRench User Group"}
 -
  title: "Contacts"
  links:
   - {link: "mailto:contact@cppp.fr", text: "contact@cppp.fr"}
 -
  title: "FAQ"
  links:
   - {permalink: "/cod/", text: "Code of Conduct"}
 -
  title: "Artists"
  links:
   - {link: "https://www.behance.net/larousselu7b60", text: "Graphic Design: Lucie Larousse"}
   - {link: "http://filledacote.com/", text: "Photography: La Fille d'à Côté"}

# Blog
blogTitle: "Latest news"
blogCommentsEnabled: false

# Speakers List Block
showSessions: true

# Team Block
teamBlockTitle: "About us"
aboutUs: 'CPPP is brought to you by the C++ FRench User Group. We also organize <a href="https://www.meetup.com/fr-FR/User-Group-Cpp-Francophone/">the Paris C++ Meetups</a> and aim at helping the French speaking C++ community all around the world.'

# Logistics Find Way Block
findWayTitle: "Find your way here"
findWayDistance: "Distance"
logisticsMapCenterCoordinates: "49.056728, 3.117289"
logisticsMapMobileCenterCoordinates: "48.335365, 23.711648"
logisticsMapAutoDirections: false

# Logistics Direction Details Block
directionDetailsImage: "direction-details.jpg"
directionDetailsTitle: "Come to CPPP"
directionDetailsCards:
 - {title: "From the Airport", information: 'There are two internation airports in Paris, Charles de Gaulle and Orly. Both have convenient access to the center of Paris through public transportation and cost around 50? to go to/from by taxi. <a href="https://www.parisaeroport.fr/en/passengers/flights">The joined website for both Paris international airports.</a>.'}
 - {title: "Public Transit", information: 'Paris is very well covered with public transportation. The UIC-P is near RER-C "Champ de Mars - Tour Eiffel" station and Metro line 6 "Bir Hakeim" station. To prepare your travel, you can use <a href="https://www.ratp.fr/en">the RATP website.</a>'}
 - {title: "Hotels", information: 'The venue is in a very touristic area, surrounded by high end hotels that are quickly full. If you want alternatives, you might want to look at hotels either along the Metro line 6 or along the RER-C between "Champ de Mars - Tour Eiffel" and "Bibliothèque François Miterrand"'}
directionDetailsWideCards:
 -
  title: "Questions?"
  subCards:
   -
    title: "Hotels"
    links:
     - {link: "https://www.accorhotels.com/fr/hotel-2175-hotel-mercure-paris-centre-tour-eiffel/index.shtml?adults=&children=&nights=&dateIn=", text: "Hotel Mercure Paris Centre Tour Eiffel"}
     - {link: "https://www.accorhotels.com/fr/hotel-7229-pullman-paris-tour-eiffel/index.shtml", text: "Hotel Pullman Paris Tour Eiffel"}
